package programaGestion;

import java.awt.Button;
import java.awt.Choice;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Label;
import java.awt.TextArea;
import java.awt.TextField;
import java.awt.event.WindowAdapter;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class Vista extends WindowAdapter
{
	static JFrame login = new JFrame("Login");
	static JFrame menuPrincipal = new JFrame("Menú Principal");
	static JMenuBar barraDeMenu = new JMenuBar();
	static JMenu menuProductos = new JMenu("Productos");
	static JMenu menuProveedores = new JMenu("Proveedores");
	static JMenu menuPanaderias = new JMenu("Panaderias");
	static JMenu menuVentas = new JMenu("Ventas");
	static JMenu menuAyuda = new JMenu("Ayuda");
	static JMenuItem ProductosAlta = new JMenuItem("Alta");
	static JMenuItem ProductosModificar = new JMenuItem("Modificacion");
	static JMenuItem ProductosConsultar = new JMenuItem("Consulta");
	static JMenuItem ProveedoresAlta = new JMenuItem("Alta");
	static JMenuItem ProveedoresBaja = new JMenuItem("Baja");
	static JMenuItem ProveedoresModificar = new JMenuItem("Modificacion");
	static JMenuItem ProveedoresConsultar = new JMenuItem("Consulta");
	static JMenuItem PanaderiasAlta = new JMenuItem("Alta");
	static JMenuItem PanaderiasConsultar = new JMenuItem("Consulta");
	static JMenuItem VentasAlta = new JMenuItem("Alta");
	static JMenuItem VentasConsultar = new JMenuItem("Consulta");
	static JMenuItem Ayuda = new JMenuItem("Ayuda");
	static JDialog errorLogin = new JDialog(login,"ERROR", true);
	static JLabel lblUsuario = new JLabel("Usuario:");
	static JLabel lblContraseña = new JLabel("Contraseña:");
	static JTextField txtUsuario = new JTextField(20); 
	static JPasswordField txtClave = new JPasswordField(20);
	static Button btnAceptar = new Button("Aceptar");
	static Button btnBorrar = new Button("Borrar");
	static Button btnErrorLoginVolver = new Button("Volver");
	static JLabel lblErrorLogin = new JLabel("Contraseña incorrecta");
	static Dialog altaProducto = new Dialog(menuPrincipal,"ALTA DE PRODUCTOS", true);
	static Label lblAPNombreProducto = new Label("Nombre del producto");
	static Label lblAPPrecioProducto = new Label("Precio del producto");
	static Label lblAPStockProducto = new Label("Cantidad del producto");
	static Label lblAPDescripcionProducto = new Label("Descripción del producto");
	static Label lblAPProveedorProducto = new Label("Proveedor del producto");
	static TextField txtAPNombreProducto = new TextField(20);
	static TextField txtAPPrecioProducto = new TextField(20);
	static TextField txtAPStockProducto = new TextField(20);
	static TextArea taAPDescripcionProducto = new TextArea(5,15);
	static Choice choAPProveedorProducto = new Choice();
	static Button btnAProdAceptar = new Button("Aceptar");
	static Button btnAProdBorrar = new Button("Borrar");
	static Frame modificacionProducto = new Frame("MODIFICACION DE PRODUCTOS");
	static Dialog modificacionProductoConfirmacion = new Dialog(modificacionProducto,"MODIFICACION", true);
	static Label lblMPNombreProducto = new Label("Nombre del producto");
	static Label lblMPPrecioProducto = new Label("Precio del producto");
	static Label lblMPStockProducto = new Label("Cantidad del producto");
	static Label lblMPDescripcionProducto = new Label("Descripción producto");
	static Label lblMPProveedorProducto = new Label("Proveedor del producto");
	static TextField txtMPNombreProducto = new TextField(20);
	static TextField txtMPPrecioProducto = new TextField(20);
	static TextField txtMPStockProducto = new TextField(20);
	static TextArea taMPDescripcionProducto = new TextArea(5,20);
	static Choice choMPProveedorProducto = new Choice();
	static Choice choModificacionProducto = new Choice();
	static Button btnMProdConfirmar = new Button("Confirmar");
	static Button btnMProdVolver = new Button("Volver");
	static Label lblModificacionProducto = new Label("Modifica los datos del proveedor que se requiera:");
	static Button btnMProdAceptar = new Button("Aceptar");
	static Frame consultaProducto = new Frame("CONSULTA DE PRODUCTOS");
	static Label lblConsultaProducto = new Label("Estos son los productos disponibles en la actualidad");
	static Choice choConsultaProducto = new Choice();
	static TextArea taConsultaProducto = new TextArea(10,60);
	static Button btnCProdExportarPDF = new Button("Exportar a PDF");
	static Dialog altaProveedor = new Dialog(menuPrincipal,"ALTA DE PROVEEDORES", true);
	static Label lblAPNombreProveedor = new Label("Nombre del proveedor");
	static Label lblAPTelefonoProveedor = new Label("Teléfono del proveedor");
	static Label lblAPNIFProveedor = new Label("NIF del proveedor");
	static TextField txtAPNombreProveedor = new TextField(20);
	static TextField txtAPTelefonoProveedor = new TextField(20);
	static TextField txtAPNIFProveedor = new TextField(20);
	static Button btnAProvAceptar = new Button("Aceptar");
	static Button btnAProvBorrar = new Button("Borrar");
	static Frame bajaProveedor = new Frame("BAJA DE PROVEEDORES");
	static Dialog bajaProveedorConfirmacion = new Dialog(bajaProveedor,"CONFIRMACION", true);
	static Label lblBajaProveedor = new Label("Elige el proveedor a borrar:");
	static Label lblBajaProveedorConfirmacion = new Label("¿Seguro que quieres borrar este proveedor?");
	static Choice choBajaProveedor = new Choice();
	static Button btnBProvAceptar = new Button("Aceptar");
	static Button btnBProvConfirmar = new Button("Confirmar");
	static Button btnBProvVolver = new Button("Volver");
	static Frame modificacionProveedor = new Frame("MODIFICACION DE PROVEEDORES");
	static Dialog modificacionProveedorConfirmacion = new Dialog(modificacionProducto,"MODIFICACION", true);
	static Label lblMPNombreProveedor = new Label("Nombre del proveedor");
	static Label lblMPTelefonoProveedor = new Label("Teléfono del proveedor");
	static Label lblMPNIFProveedor = new Label("NIF del proveedor");
	static TextField txtMPNombreProveedor = new TextField(20);
	static TextField txtMPTelefonoProveedor = new TextField(20);
	static TextField txtMPNIFProveedor = new TextField(20);
	static Choice choModificacionProveedor = new Choice();
	static Button btnMProvConfirmar = new Button("Confirmar");
	static Button btnMProvVolver = new Button("Volver");
	static Label lblModificacionProveedor = new Label("Modifica los datos del proveedor que se requiera:");
	static Button btnMProvAceptar = new Button("Aceptar");
	static Frame consultaProveedor = new Frame("CONSULTA DE PROVEEDORES");
	static Label lblConsultaProveedor = new Label("Estos son los proveedores activos en la actualidad");
	static Choice choConsultaProveedor = new Choice();
	static TextArea taConsultaProveedor = new TextArea(10,60);
	static Button btnCProvExportarPDF = new Button("Exportar a PDF");
	static Frame altaPanaderia = new Frame("ALTA DE PANADERIAS");
	static Label lblAPDireccionPanaderia = new Label("Dirección de la panaderia");
	static TextField txtAPDireccionPanaderia = new TextField(20);
	static Button btnAPAceptar = new Button("Aceptar");
	static Button btnAPBorrar = new Button("Borrar");
	static Frame consultarPanaderia = new Frame("CONSULTA DE PANADERÍAS");
	static Label lblConsultarPanaderia = new Label("Estos son las panaderías activas en la actualidad");
	static Choice choConsultarPanaderia = new Choice();
	static TextArea taConsultarPanaderia = new TextArea(10,60);
	static Button btnCPExportarPDF = new Button("Exportar a PDF");
	static Frame altaVenta = new Frame("ALTA DE VENTAS");
	static Label lblAVPanaderiaVenta = new Label("Selecciona una panadería");
	static Label lblAVProductoVenta = new Label("Selecciona un producto");
	static Label lblAVFechaVenta = new Label("Indica una fecha");
	static Choice choAVPanaderiaVenta = new Choice();
	static Choice choAVProductoVenta = new Choice();
	static TextField txtAVFechaVenta = new TextField(20);
	static Button btnAVAceptar = new Button("Aceptar");
	static Button btnAVBorrar = new Button("Borrar");
	static Dialog altaVentaConfirmacion = new Dialog(altaVenta,"ERROR, tienes que elegir alguno", true);
	static Frame consultaVenta = new Frame("CONSULTA DE VENTAS");
	static Label lblConsultaVenta = new Label("Estas son las ventas realizadas");
	static Choice choConsultaVenta = new Choice();
	static TextArea taConsultaVenta = new TextArea(10,60);
	static Button btnCVExportarPDF = new Button("Exportar a PDF");
}
